export let portfolio = {
  CWEN: {
    symbol: "CWEN",
    companyName: "",
    numberOfShares: 81777798,
    stockValueUSD: 0,
    GW: 5,
    holdingVolume: 1000,
    holdingValueUSD: 0,
    CO2avoidedPerStock: 0,
    CO2avoidedHolding: 0,
  },
  BEP: {
    symbol: "BEP",
    companyName: "",
    numberOfShares: 172203342,
    stockValueUSD: 0,
    GW: 8.05,
    holdingVolume: 2000,
    holdingValueUSD: 0,
    CO2avoidedPerStock: 0,
    CO2avoidedHolding: 0,
  },
  NEE: {
    symbol: "NEE",
    companyName: "",
    numberOfShares: 1962137094,
    stockValueUSD: 0,
    GW: 45.5,
    holdingVolume: 3000,
    holdingValueUSD: 0,
    CO2avoidedPerStock: 0,
    CO2avoidedHolding: 0,
  },
  AZRE: {
    symbol: "AZRE",
    companyName: "",
    numberOfShares: 48332573,
    stockValueUSD: 0,
    GW: 1,
    holdingVolume: 100,
    holdingValueUSD: 0,
    CO2avoidedPerStock: 0,
    CO2avoidedHolding: 0,
  },
  BLX: {
    symbol: "BLX",
    companyName: "",
    numberOfShares: 102618702,
    stockValueUSD: 0,
    GW: 2.45,
    holdingVolume: 200,
    holdingValueUSD: 0,
    CO2avoidedPerStock: 0,
    CO2avoidedHolding: 0,
  },
};
