import CompanyCard from "../components/fundContainerComps/BaseCompanyCard";
import ContainerDevelopmentCard from "../components/fundContainerComps/ContainerDevelopmentCard";

const portfolioEnergy = [
  {
    id: "1",
    company: "Clearway Energy Inc",
    offer: "Wind energy",
    image: "/fundImages/cwen.jpg",
    about:
      "Built for the 21st century, Clearway is focused on providing customers with low cost, clean power generated by solar and wind across the U.S.",
  },
  {
    id: "2",
    company: "Brookfield Renewable Partners",
    offer: "Solar energy",
    image: "/fundImages/bep.jpg",
    about:
      "SunPower Corporation is an American company specializing in solar power generation and energy storage.",
  },
  {
    id: "3",
    company: "Next Era Energy",
    offer: "Wind, Solar, Hydro energy",
    image: "/fundImages/nee.jpg",
    about:
      "As one of America's largest capital investors in infrastructure, with between $50 and $55 billion in new infrastructure investments planned through 2022, we're helping ensure that the next energy to power our dreams will be American energy.      ",
  },
  {
    id: "4",
    company: "Azure Power",
    offer: "Solar energy",
    image: "/fundImages/azre.jpg",
    about: "A leading independent renewable power producer in India.",
  },
  {
    id: "5",
    company: "Banco Latinoamericano de Comercio Exterior",
    offer: "Mix",
    image: "/fundImages/blx.jpg",
    about: "A leading independent renewable power producer in Latin America.",
  },
];

const portfolioCarbonCapture = [
  {
    id: "1",
    company: "Aker carbon capture AS",
    offer: "Carbon capture",
    image: "/fundImages/aker.jpg",
    about:
      "Aker Carbon Capture’s market-leading technology is validated by an extensive track-record and long-term operations at industrial scale. Aker Carbon Capture technology is cost-effective, robust and flexible, and it can be applied to existing plants or new builds. Our process technology has more than 50,000 operating hours and is certified by DNV GL for multiple applications.",
  },
  {
    id: "2",
    company: "Fuel cell energy",
    offer: "Fuel cells and carbon recyceling",
    image: "/fundImages/fuelenergy.jpg",
    about:
      "FuelCell Energy, Inc. (NASDAQ: FCEL) is a global leader in fuel cell technology with a purpose of utilizing its proprietary, state-of-the-art fuel cell platforms to enable a world empowered by clean energy.",
  },
  {
    id: "3",
    company: "Bloomenergy",
    offer: "Fuel cells and carbon recyceling",
    image: "/fundImages/bloom.jpg",
    about:
      "Powering our planet with resilient, sustainable, and predictable energy is the defining challenge of our time. Bloom empowers businesses and communities to take charge of their future with abundant, clean energy without compromises.",
  },
  {
    id: "4",
    company: "Ballard",
    offer: "Fuel cells",
    image: "/fundImages/ballard.jpg",
    about:
      "Ballard Power is the leading global provider of innovative clean energy fuel cell solutions that offer superior performance at a reduced operating cost.",
  },
];

function Fund() {
  return (
    <div className="mt-8 mx-8">
      <ContainerDevelopmentCard />
      <h3 className="mt-20 text-lg leading-6 font-medium text-gray-900">
        Portfolio
      </h3>
      <h1 className="mt-8 font-medium border-b-2 border-terra-purple-100">
        Clean energy
      </h1>
      <div className="grid lg:grid-cols-3 gap-10 mt-4 mb-20">
        {portfolioEnergy.map((company) => (
          <CompanyCard
            key={company.id}
            name={company.company}
            offer={company.offer}
            about={company.about}
            image={company.image}
          />
        ))}
      </div>
      <h1 className="mt-8 font-medium border-b-2 border-terra-purple-100">
        Carbon capture and fuel cells
      </h1>
      <div className="grid lg:grid-cols-3 gap-10 mt-4">
        {portfolioCarbonCapture.map((company) => (
          <CompanyCard
            key={company.id}
            name={company.company}
            offer={company.offer}
            about={company.about}
            image={company.image}
          />
        ))}
      </div>
    </div>
  );
}

export default Fund;
